name: Android UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
  
jobs:
  instrumented-tests:
    runs-on: macos-latest # Apple Silicon
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run instrumented tests on ARM emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: arm64-v8a
          profile: pixel_5
          script: ./gradlew connectedAndroidTest


      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run instrumented tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: pixel_5
          script: ./gradlew connectedAndroidTest
